### ISSUE TITLE
Gerber files missing

### ISSUE THREAD

**Issue by pascal-mignot-urca** [Dackara/Clamp_Meter#1]
Gerber files are missing.

**Comment by Dackara** [comment]
Hello,
Indeed, because as indicated, the project is under development, the first debugging revealed errors in the hardware that were repaired but due to lack of time and financial means recently, I was not able to launch a new PCB manufacturing to check that there were no more errors...
The gerber files will be added as soon as the project is no longer in the development phase.
Unfortunately, I cannot comment on a possible delay, sorry.
